### ISSUE TITLE
Can't disable hotReloading in JSX

### ISSUE THREAD

**Issue by robrkerr** [geelen/plugin-live-jsx#1]
I added `__hotReload = false` to my jsx file but it is still being hot-reloaded and in the browser I see that the `.jsx!eval` file is not looking for whether `__hotReload` is set:

```
         __jsxHot.LineGraph = __reactHotApi((function(_) {
           return __ReactMount._instancesByReactRootID;
         }));
       var hotted = __jsxHot.LineGraph(LineGraph);
       $__export("__hotReload", __hotReload = (function() {
         return false;
       }));
     } else {
       $__export("__hotReload", __hotReload = true);
     }
   }
 };
});
```

**Comment by geelen** [comment]
`v0.0.2` published. Now you can do `__hotReload = false` at any point in your JSX file and it won't try to be live-reloaded.
